---
# Note to self, is this step really needed?
- name: "CLOUDFLARE: Verify that FQDN is publicly resolvable"
  ansible.builtin.uri:
    url: "https://cloudflare-dns.com/dns-query?name={{ rport_fqdn }}"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
    headers:
      accept: application/dns-json
  register: cloudflare_dns_output
  failed_when: cloudflare_dns_output.json.Status != 0

- name: "SYSTEM: Install prereq packages"
  ansible.builtin.apt:
    name: "{{ rport_prereq }}"
    state: present
    update_cache: true

- name: "SYSTEM: Add rport user"
  ansible.builtin.user:
    name: rport
    comment: rport user
    home: /var/lib/rport
    shell: /bin/false

- name: "GUACAMOLE: Install"
  ansible.builtin.apt:
    deb: "https://bitbucket.org/cloudradar/rport-guacamole/downloads/rport-guacamole_{{ rport_guacamole_version }}_{{ ansible_distribution|lower }}_{{ ansible_distribution_release|lower }}_{{ ansible_architecture }}.deb"
    state: present

- name: "noVNC: Download"
  ansible.builtin.unarchive:
    src: "https://github.com/novnc/noVNC/archive/refs/tags/v{{ rport_novnc_version }}.zip"
    dest: /var/lib/rport/
    creates: /var/lib/rport/noVNC-{{ rport_novnc_version }}
    owner: rport
    group: rport
    remote_src: yes

- name: "RPORT: Install"
  block:
    - name: "RPORT: Download"
      ansible.builtin.get_url:
        url: "https://download.rport.io/rportd/{{ rport_release }}/latest.php?arch={{ ansible_architecture }}"
        dest: /tmp/rportd.tar.gz

    - name: "RPORT: install bin"
      ansible.builtin.unarchive:
        src: /tmp/rportd.tar.gz
        dest: /usr/local/bin/
        include: rportd
        creates: /usr/local/bin/rportd
        remote_src: true

    - name: "RPORT: Ensure /etc/rport/ exists"
      ansible.builtin.file:
        path: /etc/rport
        state: directory
        owner: rport
        group: rport

    - name: "RPORT: Ensure /var/log/rport/ exists"
      ansible.builtin.file:
        path: /var/log/rport
        state: directory
        owner: rport
        group: rport

    # Note: This should perhaps be removed
    - name: "RPORT: Install example config"
      ansible.builtin.unarchive:
        src: /tmp/rportd.tar.gz
        dest: /etc/rport/
        include: rportd.example.conf   
        creates: /etc/rport/rportd.example.conf
        remote_src: true

    - name: "RPORT: Install config from template"
      ansible.builtin.template:
        src: rportd.conf.j2
        dest: /etc/rport/rportd.conf
...
